services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Volume para o código local ser refletido no container
    ports:
      - "5173:5173"  # Porta exposta para a aplicação frontend
    depends_on:
      - git-clone  # Garante que o git-clone aconteça antes de rodar a aplicação
    networks:
      - app-network  # Rede compartilhada (caso haja outros serviços no futuro)
    command: ["yarn", "dev", "--host"]  # Comando para rodar a aplicação frontend

  git-clone:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/gabrielabade/devburger-interface.git /app &&
        exit
      "
    volumes:
      - .:/app  # Mapeia o diretório de trabalho local para o container
    networks:
      - app-network  # Rede compartilhada com a aplicação frontend

networks:
  app-network:
    driver: bridge  # Rede bridge para comunicação entre containers (não é estritamente necessário sem backend)